# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'XDLANFileTransferSDKDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for XDLANFileTransferSDKDemo
  
  pod 'CocoaAsyncSocket', '~> 7.5.0'
  pod 'XDCommonLib', '~> 0.0.1.9'


  target 'XDLANFileTransferSDKDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XDLANFileTransferSDKDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
